# -*- coding: utf-8 -*-
"""data in milk deri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOCQAh7SFWGgimzmmCOnQn8jCk7Lc2Fc
"""

import pandas as  pd

import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

df=pd.read_csv("/content/sample_data/milknew.csv")

df.info()

df.tail()

df.shape

df.describe()

df.head()

df.Colour

df.isnull().sum()

numerical_cols = df.select_dtypes(include=np.number).columns
for col in numerical_cols:
    df.boxplot(column=col)
    plt.title(f'Boxplot of {col}')
    plt.show()

df.columns

df['Grade'].unique()

df['Taste'].unique()

df.boxplot()

df.skew

from sklearn import preprocessing
le=preprocessing.LabelEncoder()
df['Grade']=le.fit_transform(df['Grade'])
df['Grade'].unique()

quantile1=df["Temprature"].quantile(0.25)
quantile2=df["Temprature"].quantile(0.75)
df["Temprature"]=np.where(df["Temprature"]<quantile1,quantile1,df["Temprature"])
df["Temprature"]=np.where(df["Temprature"]>quantile2,quantile2,df["Temprature"])

df["Temprature"].skew()

quantile1=df["Colour"].quantile(0.25)
quantile2=df["Colour"].quantile(0.75)
df["Colour"]=np.where(df["Colour"]<quantile1,quantile1,df["Colour"])
df["Colour"]=np.where(df["Colour"]>quantile2,quantile2,df["Colour"])

co=round(df["Colour"].skew(),6)
print(co)

quantile1=df["pH"].quantile(0.25)
quantile2=df["pH"].quantile(0.75)
df["pH"]=np.where(df["pH"]<quantile1,quantile1,df["pH"])
df["pH"]=np.where(df["pH"]>quantile2,quantile2,df["pH"])

df["pH"].skew()

plt.figure(figsize=(5,2))
sns.histplot(df['Grade'])
plt.show()

sns.pairplot(df,hue="Grade",height=3)

correlation=df.corr()
correlation

from matplotlib import pyplot as plt
correlation.plot(kind='scatter', x='pH', y='Temprature', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

X= df.drop("Temprature", axis = 1)
X

from matplotlib import pyplot as plt
_df_13['pH'].plot(kind='line', figsize=(8, 4), title='pH')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['pH']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('pH')

y= df["Temprature"]
X= df.drop("Temprature", axis = 1)
X

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,train_size = 0.80,
    random_state = 1)

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train,y_train)



print("Coefficients:", lr.coef_)
print("Intercept:", lr.intercept_)

